site_name: Dutch Wild West
theme:
  name: material
  language: nl
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: black
nav:
  - Algemene Plaatselijke Verordening: "index.md"
  - //:
    - Tutorial Subsection: "pages/help/test.md"
  - //: "pages/test1.md"
  - //: "pages/test2.md"